name: Production Deployment

on:
  workflow_dispatch: {}

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deliver Docker Compose file to production
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.PROD_SERVER_IP }}
          username: ${{ vars.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "dowa/"

      - name: Run Docker Compose on production server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.PROD_SERVER_IP }}
          username: ${{ vars.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          port: 22
          script: |
            cd dowa
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d