name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Application Version
        id: semver-app
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true
            
# Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

# Build + Push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "Using image: $IMAGE"

          docker build \
            -t "$IMAGE:staging" \
            -t "$IMAGE:${{ steps.semver-app.outputs.version }}" \
            -f DevOpsWebApplication/Dockerfile \
            .

          docker push "$IMAGE:staging"
          docker push "$IMAGE:${{ steps.semver-app.outputs.version }}"

# Create GitHub Release
      - name: Create release notes
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semver-app.outputs.version }}
          generateReleaseNotes: true
          body: |
            This release includes the following container image:
            ghcr.io/${{ github.repository_owner }}/devopswebapplication:${{ steps.semver-app.outputs.version }}
            
      - name: Deliver Docker Compose file to staging
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "dowa/"

      - name: Run Docker Compose on staging server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd dowa
            docker compose pull
            docker compose up -d